name: Deploy Pipeline For workato Higher Environments
on:
  release:
    types: [published,updated]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Set the variables
        run: cat /home/runner/work/_temp/_github_workflow/event.json
    
